/**
 * Translates common MySQL-specific syntax to SQLite-compatible equivalents.
 * Applied before the query guard. Covers what a typical intro database class uses.
 *
 * Statements generated by this translation (PRAGMA, sqlite_master queries) are
 * marked `internal: true` so the route can bypass the query guard for them.
 */

export interface TranslatedStatement {
  sql: string
  /** True when this statement was generated by the translation layer, not typed by the user.
   *  Internal statements bypass the query guard since we produced them. */
  internal: boolean
}

export interface CompatResult {
  statements: TranslatedStatement[]
}

export function mysqlToSqlite(raw: string): CompatResult {
  const stmts = splitOnSemicolons(raw)
  const statements: TranslatedStatement[] = []
  let hasDDL = false

  for (const stmt of stmts) {
    const trimmed = stmt.trim()
    if (!trimmed) continue
    const result = translateOne(trimmed)
    if (result !== null) {
      statements.push({ ...result, sql: convertStringEscapes(result.sql) })
      if (/^(?:CREATE|DROP)\s+TABLE\b/i.test(result.sql)) hasDDL = true
    }
  }

  // Multi-statement DDL (like a MySQL dump) needs FK enforcement disabled
  // because tables may be created/populated in any order.
  if (hasDDL && statements.length > 1) {
    statements.unshift({ sql: 'PRAGMA foreign_keys = OFF', internal: true })
    statements.push({ sql: 'PRAGMA foreign_keys = ON', internal: true })
  }

  return { statements }
}

// ---------------------------------------------------------------------------
// Per-statement translation
// ---------------------------------------------------------------------------

function translateOne(stmt: string): TranslatedStatement | null {
  // DROP DATABASE ... → skip (SQLite has no databases)
  if (/^DROP\s+DATABASE\b/i.test(stmt)) return null

  // CREATE DATABASE ... → skip
  if (/^CREATE\s+DATABASE\b/i.test(stmt)) return null

  // USE <dbname> → skip (SQLite has one DB per file)
  if (/^USE\s+`?\w+`?\s*$/i.test(stmt)) return null

  // LOCK TABLES ... → skip (SQLite has no table locking)
  if (/^LOCK\s+TABLES\b/i.test(stmt)) return null

  // UNLOCK TABLES → skip
  if (/^UNLOCK\s+TABLES\b/i.test(stmt)) return null

  // SET ... → skip (MySQL session variables not supported in SQLite)
  if (/^SET\b/i.test(stmt)) return null

  // SHOW DATABASES → skip
  if (/^SHOW\s+DATABASES\s*$/i.test(stmt)) return null

  // SHOW TABLES → sqlite_master query
  if (/^SHOW\s+TABLES\s*$/i.test(stmt)) {
    return {
      sql: "SELECT name AS Tables FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name",
      internal: true,
    }
  }

  // DESCRIBE <table> / DESC <table>
  const descMatch = stmt.match(/^(?:DESCRIBE|DESC)\s+(`?\w+`?)\s*$/i)
  if (descMatch) {
    const table = descMatch[1].replace(/`/g, '')
    return { sql: `PRAGMA table_info(${table})`, internal: true }
  }

  // SHOW COLUMNS FROM <table>
  const showColMatch = stmt.match(/^SHOW\s+COLUMNS\s+FROM\s+(`?\w+`?)\s*$/i)
  if (showColMatch) {
    const table = showColMatch[1].replace(/`/g, '')
    return { sql: `PRAGMA table_info(${table})`, internal: true }
  }

  // CREATE TABLE: apply DDL-level translations
  if (/^CREATE\s+(?:TEMPORARY\s+)?TABLE\b/i.test(stmt)) {
    return { sql: translateCreateTable(stmt), internal: false }
  }

  // Everything else: apply general syntax translations
  return { sql: translateGeneral(stmt), internal: false }
}

// ---------------------------------------------------------------------------
// CREATE TABLE translation
// ---------------------------------------------------------------------------

function translateCreateTable(sql: string): string {
  let s = sql

  // Remove table-level options that appear after the closing ')':
  // ENGINE=InnoDB, DEFAULT CHARSET=utf8mb4, AUTO_INCREMENT=100, COLLATE=..., etc.
  s = s.replace(
    /\)\s*((?:ENGINE|AUTO_INCREMENT|DEFAULT\s+CHARSET|CHARSET|CHARACTER\s+SET|COLLATE|ROW_FORMAT)\s*=\s*\S+\s*)*(;?\s*)$/i,
    ')'
  )

  // Remove column-level AUTO_INCREMENT (SQLite INTEGER PRIMARY KEY auto-increments)
  s = s.replace(/\bAUTO_INCREMENT\b/gi, '')

  // Remove UNSIGNED, ZEROFILL (SQLite has no unsigned types)
  s = s.replace(/\b(?:UNSIGNED|ZEROFILL)\b/gi, '')

  // Remove CHARACTER SET ... and COLLATE ... in column definitions
  s = s.replace(/\bCHARACTER\s+SET\s+\w+\b/gi, '')
  s = s.replace(/\bCOLLATE\s+[\w_]+\b/gi, '')

  // Remove COMMENT '...' in column definitions
  s = s.replace(/\bCOMMENT\s+'(?:[^'\\]|\\.)*'/gi, '')

  // Remove inline KEY / INDEX definitions (must be separate CREATE INDEX in SQLite)
  // Names may still be backtick-quoted at this point, so include `? around \w+
  s = s.replace(/,\s*(?:UNIQUE\s+)?(?:INDEX|KEY)\s+`?\w+`?\s*\([^)]+\)/gi, '')
  s = s.replace(/,\s*(?:UNIQUE\s+)?(?:INDEX|KEY)\s*\([^)]+\)/gi, '')

  // ENUM(...) / SET('a','b',...) → TEXT
  s = s.replace(/\bENUM\s*\([^)]*\)/gi, 'TEXT')
  s = s.replace(/\bSET\s*\(\s*'[^)]*\)/gi, 'TEXT')

  // Type mappings (SQLite uses INTEGER, REAL, TEXT, BLOB, NUMERIC)
  s = s.replace(/\bTINYINT(?:\s*\(\d+\))?\b/gi, 'INTEGER')
  s = s.replace(/\bSMALLINT(?:\s*\(\d+\))?\b/gi, 'INTEGER')
  s = s.replace(/\bMEDIUMINT(?:\s*\(\d+\))?\b/gi, 'INTEGER')
  s = s.replace(/\bBIGINT(?:\s*\(\d+\))?\b/gi, 'INTEGER')
  s = s.replace(/\bint\b(?:\s*\(\d+\))?/gi, 'INTEGER')
  s = s.replace(/\bDOUBLE(?:\s+PRECISION)?(?:\s*\(\d+\s*,\s*\d+\))?\b/gi, 'REAL')
  s = s.replace(/\bDECIMAL\b(?:\s*\(\d+(?:\s*,\s*\d+)?\))?/gi, 'REAL')
  s = s.replace(/\bFLOAT(?:\s*\(\d+\s*,\s*\d+\))?\b/gi, 'REAL')
  s = s.replace(/\bDATETIME(?:\s*\(\d+\))?\b/gi, 'TEXT')
  s = s.replace(/\bTIMESTAMP(?:\s*\(\d+\))?\b/gi, 'TEXT')
  s = s.replace(/\b(?:TINY|MEDIUM|LONG)TEXT\b/gi, 'TEXT')
  s = s.replace(/\b(?:TINY|MEDIUM|LONG)BLOB\b/gi, 'BLOB')
  s = s.replace(/\b(?:BOOLEAN|BOOL)\b/gi, 'INTEGER')

  // Backtick identifiers → plain (SQLite uses double-quotes, but unquoted works for simple names)
  s = s.replace(/`(\w+)`/g, '$1')

  return s
}

// ---------------------------------------------------------------------------
// General statement translation (DML, SELECT, etc.)
// ---------------------------------------------------------------------------

function translateGeneral(sql: string): string {
  let s = sql

  // Backtick identifiers → plain
  s = s.replace(/`(\w+)`/g, '$1')

  // INSERT IGNORE → INSERT OR IGNORE
  s = s.replace(/\bINSERT\s+IGNORE\b/gi, 'INSERT OR IGNORE')

  // MySQL date/time functions → SQLite equivalents
  s = s.replace(/\bNOW\s*\(\s*\)/gi, "datetime('now')")
  s = s.replace(/\bCURDATE\s*\(\s*\)/gi, "date('now')")
  s = s.replace(/\bCURTIME\s*\(\s*\)/gi, "time('now')")

  // MySQL LIMIT offset, count → LIMIT count OFFSET offset
  s = s.replace(/\bLIMIT\s+(\d+)\s*,\s*(\d+)\b/gi, 'LIMIT $2 OFFSET $1')

  return s
}

// ---------------------------------------------------------------------------
// MySQL string escape conversion (\' → '', \\ → \, etc.)
// ---------------------------------------------------------------------------

function convertStringEscapes(sql: string): string {
  const out: string[] = []
  let i = 0
  let inStr = false

  while (i < sql.length) {
    const ch = sql[i]

    if (!inStr) {
      out.push(ch)
      if (ch === "'") inStr = true
      i++
    } else {
      // Inside a single-quoted string
      if (ch === '\\' && i + 1 < sql.length) {
        const next = sql[i + 1]
        if (next === "'") {
          out.push("''")   // \' → '' (SQLite quote escape)
        } else if (next === '\\') {
          out.push('\\')   // \\ → backslash literal
        } else if (next === 'n') {
          out.push('\n')
        } else if (next === 'r') {
          out.push('\r')
        } else if (next === 't') {
          out.push('\t')
        } else if (next === '0') {
          // MySQL null byte — drop silently
        } else {
          out.push(next)   // Unknown escape — keep char, drop backslash
        }
        i += 2
      } else if (ch === "'") {
        out.push("'")
        inStr = false
        i++
      } else {
        out.push(ch)
        i++
      }
    }
  }

  return out.join('')
}

// ---------------------------------------------------------------------------
// Statement splitter (respects single-quoted strings and strips comments)
// ---------------------------------------------------------------------------

function splitOnSemicolons(sql: string): string[] {
  // Strip comments first so we don't split on semicolons inside them
  const stripped = sql
    .replace(/--[^\n]*/g, ' ')
    .replace(/\/\*[\s\S]*?\*\//g, ' ')

  const stmts: string[] = []
  let current = ''
  let inString = false

  for (let i = 0; i < stripped.length; i++) {
    const ch = stripped[i]
    if (inString) {
      current += ch
      if (ch === '\\' && i + 1 < stripped.length) {
        // Backslash escape inside string — consume the next char too
        i++
        current += stripped[i]
      } else if (ch === "'") {
        inString = false
      }
    } else if (ch === "'") {
      inString = true
      current += ch
    } else if (ch === ';') {
      const trimmed = current.trim()
      if (trimmed) stmts.push(trimmed)
      current = ''
    } else {
      current += ch
    }
  }

  const last = current.trim()
  if (last) stmts.push(last)
  return stmts.length > 0 ? stmts : [sql.trim()]
}
